version: "3.7"

#Docker Networks
networks:
    app_network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local

services:
    app:
        build:
            args:
                user: rocky
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel-backend
        container_name: laravel-backend-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app_network
        depends_on:
            - db

    db:
        image: mariadb
        container_name: laravel-backend-db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel_pos
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=user
            - MARIADB_PASSWORD=root
        ports:
            - "3306:3306"
        networks:
            - app_network

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: laravel-backend-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_network
        depends_on:
            - app
            - db
